# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 0 1 1 2 3 5 8
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib_sum():
    fibs=[1,2]
    cum_sum1=2
    i=0

    while True:
        current=(fibs[i]+fibs[i+1])
        if current<=4_000_000:
            fibs.append(fibs[i]+fibs[i+1])
            i+=1
            if current%2==0:
                cum_sum1+=current
        else:
            break

    return cum_sum1

print(fib_sum())